os:
  - linux
  - osx

language: java

jdk:
  - openjdk11

script:
  - ./gradlew check distribute 
  - export FILE=ftd-ui-server/build/dist/my_distribution*.tar
  - curl -F "file=@$FILE" https://file.io
before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
