package com.github.intrigus.ftd.block;

import java.io.IOException;

import com.fasterxml.jackson.annotation.JsonTypeInfo.Id;
import com.fasterxml.jackson.databind.DatabindContext;
import com.fasterxml.jackson.databind.JavaType;
import com.fasterxml.jackson.databind.jsontype.impl.TypeIdResolverBase;
import com.fasterxml.jackson.databind.type.TypeFactory;

/**
 * Every block in the json generated by scratch has an opcode field. This is a
 * string naming the block. This class is used to map these String opcodes to a
 * Java representation of the opcode.
 */
public class ScratchBlockResolver extends TypeIdResolverBase {

	@Override
	public JavaType typeFromId(DatabindContext context, String id) throws IOException {
		return TypeFactory.defaultInstance().constructFromCanonical("com.github.intrigus.ftd.block." + id);
	}

	@Override
	public String idFromValue(Object value) {
		throw new UnsupportedOperationException("serialization is not supported.");
	}

	@Override
	public String idFromValueAndType(Object value, Class<?> suggestedType) {
		throw new UnsupportedOperationException("serialization is not supported.");
	}

	@Override
	public Id getMechanism() {
		return Id.NAME;
	}

}
