/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.github.intrigus.ftd;

import static org.junit.jupiter.api.Assertions.assertThrows;

import java.io.IOException;
import java.io.InputStream;
import java.util.stream.Stream;

import org.junit.jupiter.api.Test;
import org.junit.jupiter.params.ParameterizedTest;
import org.junit.jupiter.params.provider.Arguments;
import org.junit.jupiter.params.provider.MethodSource;

import com.github.intrigus.ftd.exception.CompilationFailedException;
import com.github.intrigus.ftd.exception.ScratchParseException;

public class ConversionTest {

	@Test
	public void testNullConversion() {
		assertThrows(NullPointerException.class, () -> {
			Sb3ToArduinoC.convertToArduinoC(null);
		});
	}

	private static Stream<Arguments> provideScratchTestFiles() {
		return Stream.of("biggertest.sb3", "all_milestone_1_blocks_modified.sb3", /* "Einparker_V1_0.sb3", */
				"motor_stop_test.sb3", "when_input_test.sb3", "all_milestone_1_blocks.sb3",
				"self_defined_func_with_args.sb3", "self_defined_func_without_args.sb3",
				"self_defined_func_with_lots_of_args.sb3")
				.map((name) -> Arguments.of(name,
						Thread.currentThread().getContextClassLoader().getResourceAsStream(name)));
	}

	@ParameterizedTest(name = "{index} {0}")
	@MethodSource("provideScratchTestFiles")
	public void testConversion(String testName, InputStream testFile) throws ScratchParseException, IOException {
		Sb3ToArduinoC.convertToArduinoC(testFile);
	}

	@ParameterizedTest(name = "{index} {0}")
	@MethodSource("provideScratchTestFiles")
	public void testCompilation(String testName, InputStream testFile)
			throws ScratchParseException, IOException, CompilationFailedException {
		ArduinoCLI.compileArduinoC(Sb3ToArduinoC.convertToArduinoC(testFile));
	}

	private static Stream<Arguments> provideScratchSingleTargetTestFiles() {
		return Stream.of("single-target.json").map(
				(name) -> Arguments.of(name, Thread.currentThread().getContextClassLoader().getResourceAsStream(name)));
	}

	@ParameterizedTest(name = "{index} {0}")
	@MethodSource("provideScratchSingleTargetTestFiles")
	public void testSingleTargetConversion(String testName, InputStream testFile)
			throws ScratchParseException, IOException {
		Sb3ToArduinoC.convertSingleTargetJsonToArduinoC(testFile);
	}

	@ParameterizedTest(name = "{index} {0}")
	@MethodSource("provideScratchSingleTargetTestFiles")
	public void testSingleTargetCompilation(String testName, InputStream testFile)
			throws ScratchParseException, IOException, CompilationFailedException {
		ArduinoCLI.compileArduinoC(Sb3ToArduinoC.convertSingleTargetJsonToArduinoC(testFile));
	}

}
